export interface Mentor {
  id: string
  name: string
  title: string
  specialization: string[]
  experience: string
  rating: number
  reviews: number
  photo: string
  bio: string
  expertise: string[]
  education: string
  languages: string[]
  availability: "Available" | "Busy" | "Offline"
  price: string
  streams: ("PCB" | "PCM" | "Commerce" | "Arts")[]
}

export const MENTORS: Mentor[] = [
  {
    id: "mentor-1",
    name: "Dr. Priya Sharma",
    title: "Medical Career Counselor",
    specialization: ["NEET Preparation", "Medical Careers", "Healthcare"],
    experience: "12 years",
    rating: 4.9,
    reviews: 156,
    photo: "/indian-woman-professional-software-engineer.jpg",
    bio: "Former AIIMS professor with extensive experience in guiding students towards medical careers. Specialized in NEET preparation and healthcare career planning with a track record of helping 500+ students achieve their medical dreams.",
    expertise: [
      "MBBS Guidance",
      "Medical Entrance Exams",
      "Healthcare Career Planning",
      "NEET Strategy",
      "Medical Research",
    ],
    education: "MBBS, MD - AIIMS Delhi",
    languages: ["English", "Hindi", "Bengali"],
    availability: "Available",
    price: "₹1,500/session",
    streams: ["PCB"],
  },
  {
    id: "mentor-2",
    name: "Rajesh Kumar",
    title: "Engineering & Tech Mentor",
    specialization: ["JEE Preparation", "Software Engineering", "Technology"],
    experience: "15 years",
    rating: 4.8,
    reviews: 203,
    photo: "/indian-professional-man-data-scientist.jpg",
    bio: "IIT graduate and tech industry veteran helping students navigate engineering careers. Expert in JEE preparation and software development guidance with experience at top tech companies like Google and Microsoft.",
    expertise: ["JEE Strategy", "Software Development", "Tech Career Planning", "Data Structures", "System Design"],
    education: "B.Tech IIT Delhi, MS Stanford",
    languages: ["English", "Hindi", "Tamil"],
    availability: "Available",
    price: "₹2,000/session",
    streams: ["PCM"],
  },
  {
    id: "mentor-3",
    name: "Anita Desai",
    title: "Commerce & Business Advisor",
    specialization: ["CA Preparation", "Business Studies", "Finance"],
    experience: "10 years",
    rating: 4.7,
    reviews: 89,
    photo: "/indian-woman-business-product-manager.jpg",
    bio: "Chartered Accountant and business consultant specializing in commerce education. Helps students with CA preparation and business career planning with expertise in financial markets and corporate strategy.",
    expertise: ["CA Foundation", "Business Planning", "Financial Literacy", "Accounting", "Investment Banking"],
    education: "B.Com, CA, MBA Finance",
    languages: ["English", "Hindi", "Gujarati"],
    availability: "Busy",
    price: "₹1,200/session",
    streams: ["Commerce"],
  },
  {
    id: "mentor-4",
    name: "Prof. Vikram Singh",
    title: "Humanities & Arts Guide",
    specialization: ["Liberal Arts", "Psychology", "Social Sciences"],
    experience: "18 years",
    rating: 4.9,
    reviews: 134,
    photo: "/indian-man-devops-engineer.jpg",
    bio: "University professor with deep expertise in humanities and social science careers. Specializes in civil services preparation and research opportunities with a passion for nurturing critical thinking.",
    expertise: [
      "Psychology Careers",
      "Civil Services",
      "Research Opportunities",
      "UPSC Preparation",
      "Academic Writing",
    ],
    education: "MA Psychology, PhD Social Sciences",
    languages: ["English", "Hindi", "Punjabi"],
    availability: "Available",
    price: "₹1,000/session",
    streams: ["Arts"],
  },
  {
    id: "mentor-5",
    name: "Dr. Meera Patel",
    title: "Research & Innovation Mentor",
    specialization: ["Research Careers", "Innovation", "Entrepreneurship"],
    experience: "14 years",
    rating: 4.8,
    reviews: 97,
    photo: "/indian-woman-ux-designer.jpg",
    bio: "Research scientist and entrepreneur helping students explore innovation careers. Expert in research methodology and startup guidance with multiple patents and successful ventures.",
    expertise: [
      "Research Methodology",
      "Startup Guidance",
      "Patent Filing",
      "Innovation Management",
      "Scientific Writing",
    ],
    education: "PhD Biotechnology, Post-doc MIT",
    languages: ["English", "Hindi", "Marathi"],
    availability: "Available",
    price: "₹1,800/session",
    streams: ["PCB", "PCM"],
  },
  {
    id: "mentor-6",
    name: "Arjun Reddy",
    title: "Digital Marketing Expert",
    specialization: ["Digital Marketing", "E-commerce", "Content Creation"],
    experience: "8 years",
    rating: 4.6,
    reviews: 76,
    photo: "/professional-indian-male-digital-marketing-mentor.jpg",
    bio: "Digital marketing strategist helping students build modern business skills. Specializes in social media marketing and online business development.",
    expertise: ["Social Media Marketing", "Content Strategy", "Online Business", "SEO/SEM", "E-commerce Strategy"],
    education: "MBA Marketing, Google Certified",
    languages: ["English", "Hindi", "Telugu"],
    availability: "Available",
    price: "₹1,300/session",
    streams: ["Commerce", "Arts"],
  },
  {
    id: "mentor-7",
    name: "Dr. Kavya Nair",
    title: "Psychology & Mental Health Counselor",
    specialization: ["Psychology", "Mental Health", "Career Counseling"],
    experience: "12 years",
    rating: 4.9,
    reviews: 145,
    photo: "/professional-indian-female-psychologist-mentor.jpg",
    bio: "Clinical psychologist specializing in career anxiety, academic stress, and mental health support for students. Expert in helping students overcome career-related challenges.",
    expertise: ["Career Anxiety", "Academic Stress", "Decision Making", "Confidence Building", "Study Skills"],
    education: "PhD Clinical Psychology, M.Phil Psychology",
    languages: ["English", "Hindi", "Malayalam"],
    availability: "Available",
    price: "₹1,600/session",
    streams: ["PCB", "PCM", "Commerce", "Arts"],
  },
  {
    id: "mentor-8",
    name: "Rohit Sharma",
    title: "Civil Services & UPSC Expert",
    specialization: ["UPSC Preparation", "Civil Services", "Public Administration"],
    experience: "15 years",
    rating: 4.8,
    reviews: 198,
    photo: "/professional-indian-male-civil-services-mentor.jpg",
    bio: "Former IAS officer and UPSC trainer with extensive experience in civil services preparation. Helps students navigate the complex UPSC examination process.",
    expertise: ["UPSC Strategy", "General Studies", "Essay Writing", "Interview Preparation", "Current Affairs"],
    education: "IAS (Retd.), MA Public Administration",
    languages: ["English", "Hindi", "Punjabi"],
    availability: "Available",
    price: "₹2,200/session",
    streams: ["Arts", "Commerce"],
  },
  {
    id: "mentor-9",
    name: "Sneha Agarwal",
    title: "CA & Finance Expert",
    specialization: ["CA Preparation", "Finance", "Taxation"],
    experience: "10 years",
    rating: 4.7,
    reviews: 112,
    photo: "/professional-indian-female-ca-mentor.jpg",
    bio: "Chartered Accountant and finance professional helping students with CA preparation and finance career guidance. Expert in taxation and financial planning.",
    expertise: ["CA Foundation", "CA Intermediate", "Taxation", "Financial Planning", "Audit"],
    education: "CA, MBA Finance",
    languages: ["English", "Hindi", "Gujarati"],
    availability: "Available",
    price: "₹1,400/session",
    streams: ["Commerce"],
  },
  {
    id: "mentor-10",
    name: "Dr. Arun Kumar",
    title: "Engineering & JEE Mentor",
    specialization: ["JEE Preparation", "Engineering", "Mathematics"],
    experience: "18 years",
    rating: 4.9,
    reviews: 234,
    photo: "/professional-indian-male-engineering-mentor.jpg",
    bio: "IIT professor and JEE expert with 18 years of teaching experience. Specializes in advanced mathematics and physics for engineering entrance exams.",
    expertise: ["JEE Advanced", "Engineering Mathematics", "Physics", "Problem Solving", "Exam Strategy"],
    education: "PhD Engineering, IIT Delhi",
    languages: ["English", "Hindi", "Tamil"],
    availability: "Available",
    price: "₹2,500/session",
    streams: ["PCM"],
  },
  {
    id: "mentor-11",
    name: "Pooja Mehta",
    title: "Creative Arts & Design Mentor",
    specialization: ["Graphic Design", "Creative Arts", "Portfolio Development"],
    experience: "9 years",
    rating: 4.7,
    reviews: 87,
    photo: "/professional-indian-female-designer-mentor.jpg",
    bio: "Creative director and design mentor helping students build careers in creative fields. Expert in graphic design, branding, and creative portfolio development.",
    expertise: ["Graphic Design", "UI/UX Design", "Branding", "Portfolio Building", "Creative Strategy"],
    education: "MFA Design, NID Ahmedabad",
    languages: ["English", "Hindi", "Marathi"],
    availability: "Available",
    price: "₹1,700/session",
    streams: ["Arts", "Commerce"],
  },
  {
    id: "mentor-12",
    name: "Dr. Vikash Singh",
    title: "Medical Career & NEET Expert",
    specialization: ["NEET Preparation", "Medical Careers", "Biology"],
    experience: "14 years",
    rating: 4.8,
    reviews: 167,
    photo: "/professional-indian-male-doctor-mentor.jpg",
    bio: "Medical doctor and NEET expert helping students achieve their medical career dreams. Specializes in biology, medical entrance preparation, and career guidance.",
    expertise: ["NEET Strategy", "Biology", "Medical Career Planning", "Entrance Exams", "Study Techniques"],
    education: "MBBS, MD Internal Medicine",
    languages: ["English", "Hindi", "Bengali"],
    availability: "Available",
    price: "₹1,900/session",
    streams: ["PCB"],
  },
  {
    id: "mentor-13",
    name: "Ravi Patel",
    title: "Data Science & AI Mentor",
    specialization: ["Data Science", "Artificial Intelligence", "Machine Learning"],
    experience: "11 years",
    rating: 4.7,
    reviews: 143,
    photo: "/professional-indian-male-data-scientist-mentor.jpg",
    bio: "Senior data scientist at a leading tech company, helping students transition into AI and data science careers. Expert in machine learning and data analytics.",
    expertise: ["Python", "Machine Learning", "Data Analytics", "AI", "Statistical Analysis"],
    education: "MS Data Science, IIT Bombay",
    languages: ["English", "Hindi", "Gujarati"],
    availability: "Available",
    price: "₹2,100/session",
    streams: ["PCM", "Commerce"],
  },
  {
    id: "mentor-14",
    name: "Nisha Gupta",
    title: "Content Writing & Journalism Mentor",
    specialization: ["Content Writing", "Journalism", "Communication"],
    experience: "8 years",
    rating: 4.5,
    reviews: 94,
    photo: "/professional-indian-female-journalist-mentor.jpg",
    bio: "Senior journalist and content strategist helping students build careers in media and communication. Expert in writing, storytelling, and digital journalism.",
    expertise: ["Content Writing", "Journalism", "Digital Media", "Storytelling", "Communication Skills"],
    education: "MA Journalism, Delhi University",
    languages: ["English", "Hindi", "Punjabi"],
    availability: "Available",
    price: "₹1,200/session",
    streams: ["Arts", "Commerce"],
  },
]

export function getMentorsByStream(stream: string): Mentor[] {
  return MENTORS.filter((mentor) => mentor.streams.includes(stream as any))
}

export function getMentorById(id: string): Mentor | undefined {
  return MENTORS.find((mentor) => mentor.id === id)
}
