-- Insert sample curriculum data
INSERT INTO public.curriculum (title, description, field, difficulty_level, duration_weeks, skills_covered, prerequisites, learning_outcomes, is_featured) VALUES
('Full Stack Web Development Bootcamp', 'Comprehensive program covering frontend and backend development with modern technologies', 'Software Development', 'beginner', 16, ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'Node.js', 'MongoDB', 'Git'], ARRAY['Basic computer skills', 'Problem-solving mindset'], ARRAY['Build responsive web applications', 'Create RESTful APIs', 'Deploy applications to cloud', 'Work with databases'], true),

('Data Science Fundamentals', 'Learn the foundations of data science including statistics, programming, and machine learning', 'Data Science', 'beginner', 12, ARRAY['Python', 'Pandas', 'NumPy', 'Matplotlib', 'Statistics', 'Machine Learning', 'SQL'], ARRAY['Basic mathematics', 'Logical thinking'], ARRAY['Analyze datasets effectively', 'Build predictive models', 'Create data visualizations', 'Make data-driven decisions'], true),

('Digital Marketing Mastery', 'Complete guide to digital marketing including SEO, social media, and analytics', 'Marketing', 'intermediate', 8, ARRAY['SEO', 'Social Media Marketing', 'Google Analytics', 'Content Marketing', 'Email Marketing', 'PPC Advertising'], ARRAY['Basic marketing knowledge', 'Familiarity with social media'], ARRAY['Create effective marketing campaigns', 'Optimize for search engines', 'Measure marketing ROI', 'Build brand presence online'], false),

('UX/UI Design Essentials', 'Learn user experience and interface design principles with hands-on projects', 'Design', 'beginner', 10, ARRAY['Figma', 'User Research', 'Wireframing', 'Prototyping', 'Design Systems', 'Usability Testing'], ARRAY['Creative thinking', 'Attention to detail'], ARRAY['Design user-centered interfaces', 'Conduct user research', 'Create interactive prototypes', 'Build design systems'], true),

('Cybersecurity Fundamentals', 'Introduction to cybersecurity concepts, threats, and defense strategies', 'Cybersecurity', 'intermediate', 14, ARRAY['Network Security', 'Ethical Hacking', 'Risk Assessment', 'Incident Response', 'Cryptography', 'Security Tools'], ARRAY['Basic networking knowledge', 'Understanding of computer systems'], ARRAY['Identify security vulnerabilities', 'Implement security measures', 'Respond to security incidents', 'Conduct security audits'], false),

('Business Analysis Professional', 'Comprehensive course on business analysis techniques and methodologies', 'Business', 'intermediate', 12, ARRAY['Requirements Analysis', 'Process Modeling', 'Stakeholder Management', 'Data Analysis', 'Project Management', 'Business Intelligence'], ARRAY['Business acumen', 'Analytical thinking'], ARRAY['Analyze business processes', 'Gather and document requirements', 'Facilitate stakeholder meetings', 'Recommend process improvements'], false),

('Mobile App Development with React Native', 'Build cross-platform mobile applications using React Native', 'Mobile Development', 'intermediate', 14, ARRAY['React Native', 'JavaScript', 'Mobile UI/UX', 'API Integration', 'App Store Deployment', 'Firebase'], ARRAY['JavaScript fundamentals', 'React basics'], ARRAY['Build native mobile apps', 'Integrate with APIs', 'Publish apps to stores', 'Implement push notifications'], true),

('Financial Analysis and Modeling', 'Learn financial analysis techniques and build financial models', 'Finance', 'advanced', 10, ARRAY['Excel', 'Financial Modeling', 'Valuation', 'Risk Analysis', 'Investment Analysis', 'Financial Reporting'], ARRAY['Accounting basics', 'Excel proficiency'], ARRAY['Build financial models', 'Perform company valuations', 'Analyze investment opportunities', 'Create financial reports'], false);
